%YAML 1.2
---
description: >-
  Arm Architecture Envelope Model FVP configured with 8 CPUs across 2 clusters
  (2x4) and 2GB DRAM.

  TODO: Validate this config.

run:
  name: FVP_Base_RevC-2xAEMvA

  rtvars:
    LOCAL_NET_PORT:
      type: string
      value: 8022
    BL1:
      type: path
      value: ${artifact:BL1}
    FIP:
      type: path
      value: ${artifact:FIP}

  params:
    --stat: null
    -C bp.vis.disable_visualisation: 1
    -C cache_state_modelled: 0
    -C bp.refcounter.non_arch_start_at_default: 1
    -C bp.refcounter.use_real_time: 0
    -C bp.ve_sysregs.exit_on_shutdown: 1
    -C bp.dram_metadata.is_enabled: 1
    -C bp.secure_memory: 1
    -C cluster0.NUM_CORES: 4
    -C cluster0.PA_SIZE: 48
    -C cluster0.ecv_support_level: 2
    -C cluster0.gicv3.cpuintf-mmap-access-level: 2
    -C cluster0.gicv3.without-DS-support: 1
    -C cluster0.gicv4.mask-virtual-interrupt: 1
    -C cluster0.has_arm_v8-6: 1
    -C cluster0.has_amu: 1
    -C cluster0.has_branch_target_exception: 1
    -C cluster0.has_rndr: 1
    -C cluster0.has_v8_7_pmu_extension: 2
    -C cluster0.stage12_tlb_size: 1024
    -C cluster0.check_memory_attributes: 0
    -C cluster0.memory_tagging_support_level: 2
    -C cluster1.NUM_CORES: 4
    -C cluster1.PA_SIZE: 48
    -C cluster1.ecv_support_level: 2
    -C cluster1.gicv3.cpuintf-mmap-access-level: 2
    -C cluster1.gicv3.without-DS-support: 1
    -C cluster1.gicv4.mask-virtual-interrupt: 1
    -C cluster1.has_arm_v8-6: 1
    -C cluster1.has_amu: 1
    -C cluster1.has_branch_target_exception: 1
    -C cluster1.has_rndr: 1
    -C cluster1.has_v8_7_pmu_extension: 2
    -C cluster1.stage12_tlb_size: 1024
    -C cluster1.check_memory_attributes: 0
    -C cluster1.memory_tagging_support_level: 2
    -C pci.pci_smmuv3.mmu.SMMU_AIDR: 2
    -C pci.pci_smmuv3.mmu.SMMU_IDR0: 0x0046123B
    -C pci.pci_smmuv3.mmu.SMMU_IDR1: 0x00600002
    -C pci.pci_smmuv3.mmu.SMMU_IDR3: 0x1714
    -C pci.pci_smmuv3.mmu.SMMU_IDR5: 0xFFFF0475
    -C pci.pci_smmuv3.mmu.SMMU_S_IDR1: 0xA0000002
    -C pci.pci_smmuv3.mmu.SMMU_S_IDR2: 0
    -C pci.pci_smmuv3.mmu.SMMU_S_IDR3: 0
    -C pci.pci_smmuv3.mmu.SMMU_ROOT_IDR0: 3
    -C pci.pci_smmuv3.mmu.SMMU_ROOT_IIDR: 0x43B
    -C pci.pci_smmuv3.mmu.root_register_page_offset: 0x20000
    -C pctl.startup: 0.0.0.0
    -C bp.smsc_91c111.enabled: 1
    -C bp.hostbridge.userNetworking: 1
    -C bp.hostbridge.userNetPorts: ${rtvar:LOCAL_NET_PORT}=22
    -C bp.secureflashloader.fname: ${rtvar:BL1}
    -C bp.flashloader0.fname: ${rtvar:FIP}
    --plugin: $$(which ScalableVectorExtension.so)

  terminals:
    bp.terminal_0:
      friendly: term0
      port_regex: 'terminal_0: Listening for serial connection on port (\d+)'
      type: stdout

    bp.terminal_1:
      friendly: term1
      port_regex: 'terminal_1: Listening for serial connection on port (\d+)'
      type: stdout

    bp.terminal_2:
      friendly: term2
      port_regex: 'terminal_2: Listening for serial connection on port (\d+)'
      type: stdout

    bp.terminal_3:
      friendly: term3
      port_regex: 'terminal_3: Listening for serial connection on port (\d+)'
      type: stdout
