%YAML 1.2
---
description: >-
  Best choice for: I want to run Linux on FVP, booting with ACPI, and have easy
  control over its command line.

  Brings together TF-A and EDK2 to provide a simple non-secure world environment
  running on FVP. Allows easy specification of the kernel image and command
  line, and rootfs at runtime (see rtvars). ACPI is provided by UEFI.

  By default (if not overriding the rtvars) a sensible command line is used that
  will set up the console for logging and attempt to mount the rootfs image from
  the FVP's virtio block device. However the default rootfs image is empty, so
  the kernel will panic when attempting to mount; the user must supply a rootfs
  if it is required that the kernel completes its boot. No default kernel image
  is supplied and the config will refuse to run unless it is explicitly
  specified.

  Note that the config will boot to the EDK2 main screen and the user must
  navigate to Boot Manager -> UEFI Shell. Then hit enter to execute startup.nsh,
  which will boot the kernel as specified. The main UART console is redirected
  to telnet and the user will be prompted to run the required telnet command in
  a separate window. This is required due to EDK2's ncurses-like output.

layers:
  - FVP_Base_RevC-2xAEMvA-base.yaml
  - tfa-base.yaml
  - edk2-base.yaml

build:
  tfa:
    params:
      BL33: ${artifact:EDK2}

run:
  rtvars:
    CMDLINE:
      type: string
      value: console=ttyAMA0 earlycon=pl011,0x1c090000 root=/dev/vda ip=dhcp

    KERNEL:
      type: path
      value: null

    ROOTFS:
      type: path
      value: ''

  params:
    -C bp.virtioblockdevice.image_path: ${rtvar:ROOTFS}
    -C cluster0.cpu0.semihosting-cwd: ${param:packagedir}

  prerun:
    # We use the FVP's and UEFI's semihosting capability to get the images into
    # the system. Wrap this up as a command in the startup.nsh along with the
    # command line. UEFI will execute this when entering its shell. Copy the
    # images to the package directory (which is the root of our semihosting
    # environment) then refer to them by its base name to UEFI.
    - cp ${rtvar:KERNEL} ${param:packagedir}
    - cat <<EOF > ${param:packagedir}/startup.nsh
    - $$(basename ${rtvar:KERNEL}) ${rtvar:CMDLINE}
    - EOF

  terminals:
    bp.terminal_0:
      friendly: tfa+edk2+linux
      type: telnet
    bp.terminal_1:
      friendly: edk2
