%YAML 1.2
---
description: >-
  Best choice for: I want to run Linux on FVP, booting with device tree, and
  have easy control over its command line.

  Builds on ns-edk2-acpi.yaml, but adds a device tree that is passed to the
  kernel to use instead of ACPI. See the description in that file for details.

  An extra rtvar is added (DTB) which allows specification of a custom device
  tree. By default (if not overriding the rtvar), the upstream kernel device
  tree is used.

layers:
  - ns-edk2-acpi.yaml
  - dt-base.yaml

run:
  rtvars:
    DTB:
      type: path
      value: ${artifact:DTB}

  prerun:
    # Override what the base layer did so that dtb=<DTB> gets added to the
    # command line. See ns-edk2-acpi.yaml for rationale on approach.
    - cp ${rtvar:DTB} ${param:packagedir}
    - cat <<EOF > ${param:packagedir}/startup.nsh
    - $$(basename ${rtvar:KERNEL}) dtb=$$(basename ${rtvar:DTB}) ${rtvar:CMDLINE}
    - EOF
