# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Trusted Firmware for A-class CPUs. This provides a baseline configuration that
  can be customized by higher layers.

  TODO: Validate this config.

build:
  tfa:
    repo:
      remote: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git
      revision: master

    params:
      PLAT: fvp
      DEBUG: 0
      LOG_LEVEL: 40
      ENABLE_SVE_FOR_NS: 1
      ENABLE_SVE_FOR_SWD: 1
      ARM_DISABLE_TRUSTED_WDOG: 1
      FVP_HW_CONFIG_DTS: fdts/fvp-base-gicv3-psci-1t.dts
      ARM_ARCH_MINOR: 5
      BRANCH_PROTECTION: 1
      CTX_INCLUDE_PAUTH_REGS: 1
      CTX_INCLUDE_MTE_REGS: 1

    build:
      # TODO: tfa has makefile dependency bug that prevents parallel make (-j > 1).
      - make BUILD_BASE=${param:builddir} ${param:join_equal} all fip

    clean:
      - make BUILD_BASE=${param:builddir} realclean

    artifacts:
      BL1: ${param:builddir}/fvp/release/bl1.bin
      BL2: ${param:builddir}/fvp/release/bl2.bin
      BL31: ${param:builddir}/fvp/release/bl31.bin
      FIP: ${param:builddir}/fvp/release/fip.bin
