# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Implements all mandatory requirements and features as well as a sensible
  selection of optional ones for the Armv8.3 architecture extension within the
  Base_RevC-2xAEMvA FVP. Intended for use as an overlay to
  FVP_Base_RevC-2xAEMvA-base.yaml.

layers:
  - arch/v8.2.yaml

build:
  tfa:
    params:
      ARM_ARCH_MINOR: 3
      CTX_INCLUDE_PAUTH_REGS: 1

run:
  params:
    -C cluster0.has_arm_v8-3: 1
    -C cluster1.has_arm_v8-3: 1
