# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Implements all mandatory requirements and features as well as a sensible
  selection of optional ones for the Armv8.5 architecture extension within the
  Base_RevC-2xAEMvA FVP. Intended for use as an overlay to
  FVP_Base_RevC-2xAEMvA-base.yaml.

layers:
  - arch/v8.4.yaml

build:
  tfa:
    params:
      ARM_ARCH_MINOR: 5
      BRANCH_PROTECTION: 1
      CTX_INCLUDE_MTE_REGS: 1

run:
  params:
    -C cluster0.has_arm_v8-5: 1
    -C cluster1.has_arm_v8-5: 1
    -C cluster0.has_branch_target_exception: 1                        # Implement Branch target identification mechanism from ARMv8.5 (FEAT_BTI). 1:feature is implemented if ARMv8.5 is enabled.
    -C cluster1.has_branch_target_exception: 1
    -C cluster0.has_rndr: 1                                           # Implement random number instructions to read from RNDR and RNDRSS random number registers from ARMv8.5 (FEAT_RNG). 1:feature is implemented if ARMv8.5 is enabled.
    -C cluster1.has_rndr: 1
    -C cluster0.memory_tagging_support_level: 3                       # Specify the memory tagging extension support level: 0, not implemented. 1, instructions and registers only are implemented (FEAT_MTE). 2, implemented (FEAT_MTE2). 3, implemented with asymmetric handling of exceptions
    -C cluster1.memory_tagging_support_level: 3
