# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Implements all mandatory requirements and features as well as a sensible
  selection of optional ones for the Armv8.0 architecture extension within the
  Base_RevC-2xAEMvA FVP. Intended for use as an overlay to
  FVP_Base_RevC-2xAEMvA-base.yaml.

build:
  tfa:
    params:
      ARM_ARCH_MINOR: 0

run:
  params:
    -C cluster0.has_16k_granule: 1                                    # Implement the 16k LPAE translation granule.
    -C cluster1.has_16k_granule: 1
