# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Implements all mandatory requirements and features as well as a sensible
  selection of optional ones for the Armv9.0 architecture extension within the
  Base_RevC-2xAEMvA FVP. Intended for use as an overlay to
  FVP_Base_RevC-2xAEMvA-base.yaml.

layers:
  - arch/v8.5.yaml

build:
  tfa:
    params:
      CTX_INCLUDE_AARCH32_REGS: 0

run:
  params:
    -C cluster0.has_arm_v9-0: 1
    -C cluster1.has_arm_v9-0: 1
    -C cluster0.max_32bit_el: 0                                       # Maximum exception level supporting AArch32 modes. -1: No Support for A32 at any EL, x:[0:3] - All the levels below supplied ELx supports A32
    -C cluster1.max_32bit_el: 0
    -C SVE.ScalableVectorExtension.has_sve2: 1                        # Whether SVE2 is implemented (FEAT_SVE2).
