# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Implements all mandatory requirements and features as well as a sensible
  selection of optional ones for the Armv9.1 architecture extension within the
  Base_RevC-2xAEMvA FVP. Intended for use as an overlay to
  FVP_Base_RevC-2xAEMvA-base.yaml.

layers:
  - arch/v8.6.yaml
  - arch/v9.0.yaml

run:
  params:
    -C cluster0.has_arm_v9-1: 1
    -C cluster1.has_arm_v9-1: 1
