# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Brings together a software stack to demonstrate Arm CCA running on FVP in a
  four-world configuration. Includes TF-A in root world, Hafnium and some demo
  secure partitions in secure world, RMM in realm world, and Linux in Normal
  world.

  In order to launch realm VMs, the user must bring their own rootfs that
  contains a realm-aware kvmtool and an RSI-aware guest kernel image.

concrete: true

layers:
  - cca-3world.yaml
  - hafnium-base.yaml

build:
  tfa:
    params:
      SPD: spmd
      SPMD_SPM_AT_SEL2: 1
      SP_LAYOUT_FILE: ${artifact:SP_LAYOUT}
      BL32: ${artifact:HAFNIUM}

  # Provides secure partitions that run under Hafnium for demonstration.
  tfa-tests:
    repo:
      remote: https://git.trustedfirmware.org/TF-A/tf-a-tests.git
      revision: v2.8

    toolchain: aarch64-none-elf-

    params:
      PLAT: fvp
      DEBUG: 1

    build:
      # TODO: tfa-tests has makefile dependency bug that prevents parallel make (-j > 1).
      - make BUILD_BASE=${param:builddir} ${param:join_equal} all pack_realm

    clean:
      - make BUILD_BASE=${param:builddir} realclean

    artifacts:
      SP_LAYOUT: ${param:builddir}/fvp/debug/sp_layout.json

run:
  terminals:
    bp.terminal_2:
      friendly: hafnium
