%YAML 1.2
---
description: >-
  EDK2 UEFI firmware implementation for the FVP.

  Builds acpica from source as part of the build process.

build:
  edk2:
    repo:
      edk2:
        remote: https://github.com/tianocore/edk2.git
        revision: master
      edk2-platforms:
        remote: https://github.com/tianocore/edk2-platforms.git
        revision: master
      acpica:
        remote: https://github.com/acpica/acpica.git
        revision: master

    prebuild:
      - export WORKSPACE=${param:sourcedir}
      - export GCC5_AARCH64_PREFIX=$$CROSS_COMPILE
      - export PACKAGES_PATH=$$WORKSPACE/edk2:$$WORKSPACE/edk2-platforms
      - export IASL_PREFIX=$$WORKSPACE/acpica/generate/unix/bin/
      - export PYTHON_COMMAND=/usr/bin/python3

    params:
      -a: AARCH64
      -t: GCC5
      -p: Platform/ARM/VExpressPkg/ArmVExpress-FVP-AArch64.dsc
      -b: RELEASE

    build:
      - make -j${param:jobs} -C acpica
      # edksetup.sh invokes unbound variables to relax temporarily.
      - set +u; source edk2/edksetup.sh; set -u
      - make -j${param:jobs} -C edk2/BaseTools
      - build -n ${param:jobs} -D EDK2_OUT_DIR=${param:builddir} ${param:join_space}

    artifacts:
      EDK2: ${param:builddir}/RELEASE_GCC5/FV/FVP_AARCH64_EFI.fd
