# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  kvmtool is a lightweight Virtual Machine Monitor that can be used, in concert
  with KVM, to create and manage virtual machines. This config fragment can be
  used to build the kvmtool binary, which is exported as an artifact called
  LKVM. Fancy optional extras which depend on 3rd party libraries are not
  enabled.

build:
  kvmtool:
    repo:
      dtc:
        remote: git://git.kernel.org/pub/scm/utils/dtc/dtc.git
        revision: master
      kvmtool:
        remote: git://git.kernel.org/pub/scm/linux/kernel/git/will/kvmtool.git
        revision: master

    toolchain: aarch64-linux-gnu-

    build:
      - export CC=$${CROSS_COMPILE}gcc
      - export ARCH=arm64
      - export LIBFDT_DIR=${param:sourcedir}/dtc/libfdt
      - make -j${param:jobs} -C dtc libfdt
      - make -j${param:jobs} -C kvmtool

    clean:
      - make -j${param:jobs} -C dtc clean
      - make -j${param:jobs} -C kvmtool clean

    artifacts:
      LKVM: ${param:sourcedir}/kvmtool/lkvm