# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
description: >-
  Linux kernel build config. Builds the kernel image and set of modules. Image
  is exported as the KERNEL artifact, while the modules are exported in a tgz
  archive as the KMODULES artifact. Modules are only built if a higher level
  layer specifies `export BUILD_KMODULES=true` in the prebuild section.

  By default the defconfig is built. Users can optionally add commands to the
  prebuild list to modify the config (e.g. `./scripts/config ...`) or even
  replace the .config, as required.

build:
  linux:
    repo:
      remote: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
      revision: v6.1

    toolchain: aarch64-none-elf-

    prebuild:
      - export BUILD_KMODULES=false
      - export ARCH=arm64
      - make -j${param:jobs} O=${param:builddir} defconfig

    build:
      # Finalize the config.
      - make -j${param:jobs} O=${param:builddir} olddefconfig

      - if [ "$$BUILD_KMODULES" = "true" ]; then
          # Make the kernel image and modules.
      -   make -j${param:jobs} O=${param:builddir} Image modules

          # Package the modules into a tgz archive.
      -   make -j${param:jobs} O=${param:builddir} INSTALL_MOD_PATH=${param:builddir}/modules modules_install
      -   tar -caf ${param:builddir}/modules.tgz -C ${param:builddir}/modules .
      -   rm -rf ${param:builddir}/modules
      - else
          # Make the kernel image.
      -   make -j${param:jobs} O=${param:builddir} Image

          # Dummy modules archive to keep artifacts happy.
      -   touch ${param:builddir}/modules.tgz
      - fi

    clean:
      - export ARCH=arm64
      - make -j${param:jobs} O=${param:builddir} clean

    artifacts:
      KERNEL: ${param:builddir}/arch/arm64/boot/Image
      KMODULES: ${param:builddir}/modules.tgz
