# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

%YAML 1.2
---
build:
  rmm:
    repo:
      remote: https://git.trustedfirmware.org/TF-RMM/tf-rmm.git
      revision: tf-rmm-v0.2.0

    toolchain: aarch64-none-elf-

    params:
      -DRMM_CONFIG: fvp_defcfg
      -DCMAKE_BUILD_TYPE: Release
      -DLOG_LEVEL: 40

    build:
      - cmake ${param:join_equal} -S . -B ${param:builddir}
      - cmake --build ${param:builddir} -j ${param:jobs}

    artifacts:
      RMM: ${param:builddir}/rmm.img
