#!/bin/bash
# Copyright (c) 2022, Arm Limited.
# SPDX-License-Identifier: MIT

realfile="$(readlink -f "$0")"
realdir="$(dirname "$realfile")"
realbase="$(basename "$realfile")"
realpy="$realdir/$realbase.py"
/usr/bin/env python3 "$realpy" "$@"
